version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=production
      - OLLAMA_URL=http://host.docker.internal:11434
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=104857600  # 100MB
      - ALLOWED_EXTENSIONS=.log,.txt,.json
    volumes:
      - uploads:/app/uploads
      - sessions:/app/uploads/sessions
      - ./backend/.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - log-analyzer

  # Frontend service  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - log-analyzer

networks:
  log-analyzer:
    driver: bridge

volumes:
  uploads:
    driver: local
  sessions:
    driver: local